webtalk_init -webtalk_dir C:/Users/andyg/Desktop/SEMESTER_1_DOCS/TFE4152 - DESIGN OF INTEGRATED CIRCUITS/EXERCISES/EX 5/SysV_EX_5/Exercise5/Exercise5.sim/sim_1/behav/xsim/xsim.dir/MealyMachine_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Nov  5 21:38:37 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2902540" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "56b788af-c48e-48e9-9029-af44bbe1d7c7" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "215b66f1129d48ae9ac648fcf0fea99e" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "41" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2304 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "215 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.01_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6488_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1143662391 -regid "" -xml C:/Users/andyg/Desktop/SEMESTER_1_DOCS/TFE4152 - DESIGN OF INTEGRATED CIRCUITS/EXERCISES/EX 5/SysV_EX_5/Exercise5/Exercise5.sim/sim_1/behav/xsim/xsim.dir/MealyMachine_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/andyg/Desktop/SEMESTER_1_DOCS/TFE4152 - DESIGN OF INTEGRATED CIRCUITS/EXERCISES/EX 5/SysV_EX_5/Exercise5/Exercise5.sim/sim_1/behav/xsim/xsim.dir/MealyMachine_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/andyg/Desktop/SEMESTER_1_DOCS/TFE4152 - DESIGN OF INTEGRATED CIRCUITS/EXERCISES/EX 5/SysV_EX_5/Exercise5/Exercise5.sim/sim_1/behav/xsim/xsim.dir/MealyMachine_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
